import numpy as np
import math

MIN_RAW_EUCLIDEAN_SCORE = 1/(1+ math.sqrt(2.0))
MAX_RAW_EUCLIDEAN_SCORE = 1.0

BOTTOM_RIGHT_GREEN_FEATURE_ID = "BOTTOM_RIGHT_GREEN"
BOTTOM_RIGHT_NEIGHBOUR_BLUE_FEATURE_ID = "BOTTOM_RIGHT_NEIGHBOUR_BLUE"
BOTTOM_RIGHT_YELLOW_FEATURE_ID = "BOTTOM_RIGHT_YELLOW"
DONUT_SHAPE_FEATURE_ID = "DONUT_SHAPE"
TOP_LEFT_PURPLE_FEATURE_ID = "TOP_LEFT_PURPLE"
TOP_RIGHT_YELLOW_FEATURE_ID = "TOP_RIGHT_YELLOW"
CORNERNESS_FEATURE_ID = "CORNERNESS"
SHARP_HOG_FEATURE_ID = "SHARP_HOG"
BORDER_GREEN_FEATURE_ID = "BORDER_GREEN"
CENTRE_YELLOW_FEATURE_ID = "CENTRE_YELLOW"
CENTRE_BLUE_FEATURE_ID = "CENTRE_BLUE"

def converScaleTo01(value, min, max):
	"""
	conver the value in min, max range scale to [0,1] range
	"""
	return float(value - min) / float(max - min)